name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Setup Maven
      uses: s4u/setup-maven-action@v1.14.0
      with:
        java-version: 21
        java-distribution: 'zulu'

    - name: Build with Maven
      run: mvn package -DSkipTests

    - name: List contents of all target directories
      run: find . -type d -name "target" -exec sh -c 'echo "Contents of {}:"; ls -l {}' \;
      
    - name: Find all NAR files
      id: find_nars
      run: echo "nars=$(find . -name '*.nar' | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Upload each NAR file as a separate artifact
      run: |
        for nar in ${{ env.nars }}; do
          artifact_name=$(basename $nar)
          echo "Uploading $artifact_name"
          gh api \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            /repos/${{ github.repository }}/actions/artifacts \
            -F "name=${artifact_name}" \
            -F "file=@${nar}"
        done
