name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Debug issue
      run: mvn help:effective-pom

    - name: Build with Maven
      run: mvn package -X

    - name: Upload NAR files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nar-files
        path: |
          **/*.nar
