name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Setup Maven
      uses: s4u/setup-maven-action@v1.14.0
      with:
        java-version: 21
        java-distribution: 'zulu'

    - name: Build with Maven
      run: mvn package -DSkipTests

    - name: List contents of all target directories
      run: find . -type d -name "target" -exec sh -c 'echo "Contents of {}:"; ls -l {}' \;
      
    - name: Upload NAR files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nar-files
        path: |
          nifi-stardog-bundle/nifi-stardog-processors/target/*.nar
          nifi-stardog-bundle/nifi-stardog-nar/target/*.nar
          **/*.nar
