name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '21'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Install Maven 3.9.6
      run: |
        wget https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.zip
        unzip apache-maven-3.9.6-bin.zip
        sudo mv apache-maven-3.9.6 /opt/maven
        sudo ln -s /opt/maven/bin/mvn /usr/bin/mvn

    - name: Debug issue
      run: mvn help:effective-pom

    - name: Build with Maven
      run: mvn package -X

    - name: Upload NAR files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nar-files
        path: |
          **/*.nar
