name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Setup Maven
      uses: s4u/setup-maven-action@v3
      with:
        java-version: 21

    - name: Debug issue
      run: mvn help:effective-pom

    - name: Build with Maven
      run: mvn package -X

    - name: Upload NAR files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nar-files
        path: |
          **/*.nar
