name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@< version >
        with:
          java-version: 21
          maven-version: 3.9.8

    - name: Build with Maven
      run: mvn package -X

    - name: Upload NAR files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nar-files
        path: |
          **/*.nar
