name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Setup Maven
      uses: s4u/setup-maven-action@v1.14.0
      with:
        java-version: 21
        java-distribution: 'zulu'

    - name: Build with Maven
      run: mvn package -DSkipTests

    - name: List contents of all target directories
      run: find . -type d -name "target" -exec sh -c 'echo "Contents of {}:"; ls -l {}' \;
      
    - name: Upload NAR and JAR files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nifi-stardog-connection-service-api-nar
        path: ./nifi-stardog-connection-service-api-nar/target/nifi-stardog-connection-service-api-nar-2.0.0.nar
    - name: Upload NAR and JAR files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nifi-stardog-services-nar
        path: ./nifi-stardog-services-nar/target/nifi-stardog-services-nar-2.0.0.nar
    - name: Upload NAR and JAR files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nifi-stardog-nar
        path: ./nifi-stardog-nar/target/nifi-stardog-nar-2.0.0.nar
    - name: Upload Processors JAR file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: nifi-stardog-processors-jar
        path: ./nifi-stardog-processors/target/nifi-stardog-processors-2.0.0.jar
